[build]
  functions = "functions"
  command = "pip install -r requirements.txt && python functions/flask_server.py"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/flask_server"
  status = 200
